"""Tests del modulo `suvalor.verificacion`.

Estos tests son completamente puros: no tocan red, Playwright ni el
filesystem real. Solo escriben archivos a `tmp_path` y validan que las
heuristicas detecten los falsos positivos mas comunes.
"""

from __future__ import annotations

from zipfile import ZipFile

import pytest

from suvalor.verificacion import (
    es_pdf_valido,
    es_reporte_fondos_valido,
    es_tabular_tesoreria_valido,
    es_xls_html_valido,
    sanitizar_pdf_bytes,
    verificar_descarga,
)


# --------------------------------------------------------------------------- #
# Helpers para fabricar contenido de archivos de test                         #
# --------------------------------------------------------------------------- #


def _pdf_minimo_valido(rel_size: int = 3_000) -> bytes:
    """Construye bytes que pasan la heuristica de `es_pdf_valido`.

    Empieza con el header `%PDF-1.4`, contenido relleno en el medio, y termina
    con el marker `%%EOF`. El size total queda alrededor de `rel_size` bytes.
    """
    header = b"%PDF-1.4\n"
    footer = b"\n%%EOF\n"
    relleno_n = max(0, rel_size - len(header) - len(footer))
    relleno = b"x" * relleno_n
    return header + relleno + footer


# --------------------------------------------------------------------------- #
# es_pdf_valido                                                               #
# --------------------------------------------------------------------------- #


class TestEsPdfValido:
    def test_pdf_valido_pasa(self, tmp_path):
        p = tmp_path / "ok.pdf"
        p.write_bytes(_pdf_minimo_valido())
        ok, motivo = es_pdf_valido(p)
        assert ok is True
        assert motivo == ""

    def test_archivo_inexistente_falla(self, tmp_path):
        ok, motivo = es_pdf_valido(tmp_path / "nope.pdf")
        assert ok is False
        assert "no existe" in motivo

    def test_archivo_vacio_falla(self, tmp_path):
        p = tmp_path / "vacio.pdf"
        p.write_bytes(b"")
        ok, motivo = es_pdf_valido(p)
        assert ok is False
        assert "0" in motivo

    def test_archivo_muy_chico_falla(self, tmp_path):
        p = tmp_path / "chico.pdf"
        # 100 bytes — pasa header check, pero size < 2048 default
        p.write_bytes(b"%PDF-1.4\n" + b"x" * 80 + b"\n%%EOF\n")
        ok, motivo = es_pdf_valido(p)
        assert ok is False
        assert "size=" in motivo

    def test_pdf_sin_eof_falla(self, tmp_path):
        # Empieza con %PDF- pero no tiene %%EOF al final.
        p = tmp_path / "sin_eof.pdf"
        p.write_bytes(b"%PDF-1.4\n" + b"x" * 5_000)
        ok, motivo = es_pdf_valido(p)
        assert ok is False
        assert "EOF" in motivo

    def test_pdf_solo_header_falla_por_size(self, tmp_path):
        # Tip: '%PDF-' solo (5 bytes) NO basta — falla por size primero.
        p = tmp_path / "solo_header.pdf"
        p.write_bytes(b"%PDF-")
        ok, motivo = es_pdf_valido(p)
        assert ok is False

    def test_html_camuflado_de_pdf_falla(self, tmp_path):
        # Cookie expirada -> server devuelve HTML de login en vez del PDF.
        p = tmp_path / "fake.pdf"
        p.write_bytes(
            b"<!DOCTYPE html><html><body><h1>Iniciar sesion</h1>"
            + b"<p>Tu sesion ha expirado.</p>" * 100
            + b"</body></html>"
        )
        ok, motivo = es_pdf_valido(p)
        assert ok is False
        # diagnostico amigable: detecta que es HTML
        assert "HTML" in motivo or "header" in motivo

    def test_html_cloudfront_504_camuflado_de_pdf_falla_con_motivo_normalizado(
        self, tmp_path
    ):
        p = tmp_path / "fb.pdf"
        p.write_bytes(
            b"<!DOCTYPE html><html><head><title>504 Gateway Timeout</title></head>"
            + b"<body><h1>ERROR: The request could not be satisfied</h1>"
            + b"<p>Generated by cloudfront (CloudFront)</p></body></html>"
        )

        ok, motivo = verificar_descarga(p, "pdf")

        assert ok is False
        assert motivo == "portal respondio HTTP 504 (CloudFront Gateway Timeout)"
        assert "jwt=" not in motivo

    def test_min_bytes_custom(self, tmp_path):
        p = tmp_path / "ok.pdf"
        p.write_bytes(_pdf_minimo_valido(rel_size=3_000))
        # con min muy alto deberia fallar
        ok, motivo = es_pdf_valido(p, min_bytes=10_000)
        assert ok is False
        assert "size=" in motivo

    def test_sanitizar_bytes_trunca_despues_ultimo_eof(self):
        pdf = _pdf_minimo_valido() + b"basura-html"
        assert sanitizar_pdf_bytes(pdf) == _pdf_minimo_valido().rstrip(b"\n")

    def test_sanitizar_bytes_es_idempotente(self):
        pdf = _pdf_minimo_valido().rstrip(b"\n")
        assert sanitizar_pdf_bytes(sanitizar_pdf_bytes(pdf)) == pdf

    def test_verificar_pdf_sanitiza_archivo_con_trailing_html(self, tmp_path):
        p = tmp_path / "pb.pdf"
        p.write_bytes(_pdf_minimo_valido() + (b"<html>footer</html>" * 200))
        ok, motivo = verificar_descarga(p, "pdf")
        assert ok is True
        assert motivo == ""
        assert p.read_bytes().endswith(b"%%EOF")

    @pytest.mark.parametrize(
        "contenido", [b"<html>login</html>", b"%PDF-1.4\n" + b"x" * 3000]
    )
    def test_verificar_pdf_no_sanitiza_html_ni_sin_eof(self, tmp_path, contenido):
        p = tmp_path / "fake.pdf"
        p.write_bytes(contenido)
        ok, motivo = verificar_descarga(p, "pdf")
        assert ok is False
        assert motivo


# --------------------------------------------------------------------------- #
# es_xls_html_valido                                                          #
# --------------------------------------------------------------------------- #


class TestEsXlsHtmlValido:
    def test_html_con_table_pasa(self, tmp_path):
        p = tmp_path / "portafolio.xls"
        contenido = (
            b"<html><body>"
            + b"<p>relleno</p>" * 200
            + b"<table border=1><tr><td>Saldo</td><td>123</td></tr></table>"
            + b"</body></html>"
        )
        p.write_bytes(contenido)
        ok, motivo = es_xls_html_valido(p)
        assert ok is True
        assert motivo == ""

    def test_html_de_login_falla(self, tmp_path):
        p = tmp_path / "fake.xls"
        # Tiene <table> pero tambien "iniciar sesion" -> debe fallar.
        contenido = (
            b"<html><body>"
            + b"x" * 3000
            + b"<form>Iniciar sesion</form>"
            + b"<table><tr><td>foo</td></tr></table>"
            + b"</body></html>"
        )
        p.write_bytes(contenido)
        ok, motivo = es_xls_html_valido(p)
        assert ok is False
        assert "login" in motivo.lower() or "iniciar" in motivo.lower()

    def test_html_sin_table_falla(self, tmp_path):
        p = tmp_path / "sin_table.xls"
        p.write_bytes(b"<html><body>" + b"x" * 3000 + b"</body></html>")
        ok, motivo = es_xls_html_valido(p)
        assert ok is False
        assert "table" in motivo.lower()

    def test_archivo_vacio_falla(self, tmp_path):
        p = tmp_path / "vacio.xls"
        p.write_bytes(b"")
        ok, motivo = es_xls_html_valido(p)
        assert ok is False
        assert "0" in motivo

    def test_archivo_inexistente_falla(self, tmp_path):
        ok, motivo = es_xls_html_valido(tmp_path / "nope.xls")
        assert ok is False
        assert "no existe" in motivo

    def test_table_case_insensitive(self, tmp_path):
        p = tmp_path / "ok_upper.xls"
        contenido = (
            b"<HTML><BODY>"
            + b"y" * 3000
            + b"<TABLE><TR><TD>x</TD></TR></TABLE></BODY></HTML>"
        )
        p.write_bytes(contenido)
        ok, motivo = es_xls_html_valido(p)
        assert ok is True


# --------------------------------------------------------------------------- #
# es_reporte_fondos_valido                                                    #
# --------------------------------------------------------------------------- #


class TestEsReporteFondosValido:
    def test_acepta_ole_xls(self, tmp_path):
        p = tmp_path / "fondos.xls"
        p.write_bytes(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + b"x" * 128)
        assert es_reporte_fondos_valido(p) == (True, "")

    def test_acepta_xlsx_con_workbook(self, tmp_path):
        p = tmp_path / "fondos.xlsx"
        with ZipFile(p, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types />")
            zf.writestr("xl/workbook.xml", "<workbook />")
        assert es_reporte_fondos_valido(p) == (True, "")

    def test_acepta_html_con_tabla(self, tmp_path):
        p = tmp_path / "fondos.xls"
        p.write_text(
            "<html><body><table><tr><th>Fecha</th></tr><tr><td>2026-01-01</td></tr></table></body></html>"
        )
        assert es_reporte_fondos_valido(p) == (True, "")

    @pytest.mark.parametrize("sep", [",", ";", "\t"])
    def test_acepta_texto_delimitado_con_header_y_fila(self, tmp_path, sep):
        p = tmp_path / "fondos.xls"
        p.write_text(f"Fecha{sep}Valor\n2026-01-01{sep}100\n", encoding="utf-8")
        assert es_reporte_fondos_valido(p) == (True, "")

    @pytest.mark.parametrize(
        "contenido",
        [
            "<html><body>Iniciar sesion<table><tr><td>x</td></tr></table></body></html>",
            "<html><body>Error de aplicacion<table><tr><td>x</td></tr></table></body></html>",
            "solo una linea sin delimitador",
            "Fecha,Valor\n2026-01-01\n",
            "PK-no-es-zip-valido",
            "\x00\x01\x02\x03",
        ],
    )
    def test_rechaza_login_error_malformed_y_magic_invalida(self, tmp_path, contenido):
        p = tmp_path / "fondos.xls"
        p.write_text(contenido, encoding="utf-8")
        ok, motivo = es_reporte_fondos_valido(p)
        assert ok is False
        assert motivo


# --------------------------------------------------------------------------- #
# es_tabular_tesoreria_valido                                                 #
# --------------------------------------------------------------------------- #


class TestEsTabularTesoreriaValido:
    def test_acepta_ole_xls_y_xlsx(self, tmp_path):
        ole = tmp_path / "tesoreria.xls"
        ole.write_bytes(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + b"x" * 128)
        xlsx = tmp_path / "tesoreria.xlsx"
        with ZipFile(xlsx, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types />")
            zf.writestr("xl/workbook.xml", "<workbook />")
        assert es_tabular_tesoreria_valido(ole) == (True, "")
        assert es_tabular_tesoreria_valido(xlsx) == (True, "")

    def test_acepta_html_con_tabla_y_celda(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text(
            "<html><body><table>"
            "<tr><th>Fecha</th><th>Valor</th></tr>"
            "<tr><td>2026-01-01</td><td>100</td></tr>"
            "</table></body></html>"
        )
        assert es_tabular_tesoreria_valido(p) == (True, "")

    @pytest.mark.parametrize("sep", [",", ";", "\t"])
    def test_acepta_texto_delimitado_con_token_requerido(self, tmp_path, sep):
        p = tmp_path / "tesoreria.xls"
        p.write_text(f"Fecha{sep}Valor\n2026-01-01{sep}100\n", encoding="utf-8")
        assert es_tabular_tesoreria_valido(p) == (True, "")

    @pytest.mark.parametrize(
        "contenido",
        [
            "",
            "<html><body>Iniciar sesion<table><tr><td>x</td></tr></table></body></html>",
            "<html><body>Error de aplicacion<table><tr><td>x</td></tr></table></body></html>",
            "foo,bar\n1,2\n",
            "Fecha,Valor\n2026-01-01\n",
            "<html><body><table><tr><th>Fecha</th><th>Valor</th></tr></table></body></html>",
            "PK-no-es-zip-valido",
            "\x00\x01\x02\x03",
        ],
    )
    def test_rechaza_inseguros_o_malformados(self, tmp_path, contenido):
        p = tmp_path / "tesoreria.xls"
        p.write_text(contenido, encoding="utf-8")
        ok, motivo = es_tabular_tesoreria_valido(p)
        assert ok is False
        assert motivo

    def test_header_only_tesoreria_es_sin_movimientos_no_exitoso(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text(
            "Fecha\tDocumento\tDetalle\tObservacion\tValor\t\r\n", encoding="utf-8"
        )

        ok, motivo = es_tabular_tesoreria_valido(p)

        assert ok is False
        assert "reporte tesoreria sin movimientos" in motivo
        assert "lineas=1" in motivo
        assert "sep_tab=5" in motivo

    def test_header_parcial_de_tesoreria_no_es_sin_movimientos(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text("Fecha\tValor\n", encoding="utf-8")

        ok, motivo = es_tabular_tesoreria_valido(p)

        assert ok is False
        assert "formato de reporte tesoreria no reconocido" in motivo
        assert "reporte tesoreria sin movimientos" not in motivo

    def test_diagnostico_formato_no_reconocido_no_filtra_contenido(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text(
            "Cuenta Cliente Confidencial,Referencia\n123456789,100\n",
            encoding="utf-8",
        )

        ok, motivo = es_tabular_tesoreria_valido(p)

        assert ok is False
        assert "formato de reporte tesoreria no reconocido" in motivo
        assert "size=" in motivo
        assert "clase=texto" in motivo
        assert "lineas=2" in motivo
        assert "sep_coma=1" in motivo
        assert "Cuenta" not in motivo
        assert "Confidencial" not in motivo
        assert "123456789" not in motivo

    def test_diagnostico_html_sin_tabla_incluye_solo_contadores(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text(
            "<html><body><table><tr><th>Fecha</th></tr></table></body></html>",
            encoding="utf-8",
        )

        ok, motivo = es_tabular_tesoreria_valido(p)

        assert ok is False
        assert "html sin tabla" in motivo
        assert "clase=html" in motivo
        assert "table=1" in motivo
        assert "tr=1" in motivo
        assert "td=0" in motivo
        assert "Fecha" not in motivo


# --------------------------------------------------------------------------- #
# verificar_descarga: despachador                                             #
# --------------------------------------------------------------------------- #


class TestVerificarDescarga:
    def test_despacha_a_pdf(self, tmp_path):
        p = tmp_path / "ok.pdf"
        p.write_bytes(_pdf_minimo_valido())
        ok, motivo = verificar_descarga(p, "pdf")
        assert ok is True

    def test_despacha_a_xls_html(self, tmp_path):
        p = tmp_path / "ok.xls"
        p.write_bytes(
            b"<html><body>"
            + b"z" * 3000
            + b"<table><tr><td>1</td></tr></table></body></html>"
        )
        ok, motivo = verificar_descarga(p, "xls_html")
        assert ok is True

    def test_despacha_a_fondos(self, tmp_path):
        p = tmp_path / "fondos.xls"
        p.write_text("Fecha\tValor\n2026-01-01\t100\n", encoding="utf-8")
        ok, motivo = verificar_descarga(p, "fondos")
        assert ok is True
        assert motivo == ""

    def test_despacha_a_tesoreria(self, tmp_path):
        p = tmp_path / "tesoreria.xls"
        p.write_text("Fecha\tValor\n2026-01-01\t100\n", encoding="utf-8")
        ok, motivo = verificar_descarga(p, "tesoreria")
        assert ok is True
        assert motivo == ""

    def test_tipo_desconocido_falla(self, tmp_path):
        p = tmp_path / "x.bin"
        p.write_bytes(b"x" * 5000)
        ok, motivo = verificar_descarga(p, "csv")
        assert ok is False
        assert "tipo" in motivo.lower() or "desconocido" in motivo.lower()

    def test_pdf_invalido_propaga_motivo(self, tmp_path):
        p = tmp_path / "vacio.pdf"
        p.write_bytes(b"")
        ok, motivo = verificar_descarga(p, "pdf")
        assert ok is False
        assert motivo  # tiene algun motivo
